bugfix: crash when `Cucumber::Messages::Group#children` is `nil` (#1819)
This change fixes the `undefined method 'map' for nil (NoMethodError)`
for `cucumber-10.2.0/lib/cucumber/formatter/message_builder.rb:144`:
`'Cucumber::Formatter::MessageBuilder#argument_group_to_message'`
caused by:

* Dec 11, 2025: https://github.com/cucumber/cucumber-ruby/pull/1805
  allows to pull `cucumber-cucumber-expressions` `19.0.0`

* Jan 21, 2026: https://github.com/cucumber/messages/pull/370
  introduce a breaking change that allows the `children` field of
  `Cucumber::Messages::Group` to be `nil`

* Jan 21, 2026: https://github.com/cucumber/cucumber-expressions/pull/387
  `ruby/lib/cucumber/cucumber_expressions/group_builder.rb` sets
  the `children` to `nil` if `empty?`

* Jan 26, 2026: The `cucumber-cucumber-expressions` `19.0.0` gem released
  and will be pulled in by `cucumber` `10.2.0` that raises the error

The fix is simply accept the `nil` value for
`Cucumber::Messages::Group#children`.